# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewAES' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewAES
    pod 'CryptoSwift'
  target 'NewAESTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewAESUITests' do
    # Pods for testing
  end

end
