# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyNetwork' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


    pod 'RxSwift'
    pod 'RxCocoa'

  # Pods for MyNetwork

  target 'MyNetworkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyNetworkUITests' do
    # Pods for testing
  end

end
