//
//  DetailInteractor.swift
//  CleanSwift_GetData
//
//  Created by brian은석 on 2021/02/02.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailBusinessLogic
{
    func getInfo(request: Detail.ShowDetail.Request)
}

protocol DetailDataStore {
    var info: Information.Detail! { get set }
}

class DetailInteractor: DetailBusinessLogic, DetailDataStore {
    var presenter: DetailPresentationLogic?
    var info: Information.Detail!
    
    // MARK: Do something
    
    func getInfo(request: Detail.ShowDetail.Request) {
        
        let response = Detail.ShowDetail.Response(detail: info)
        presenter?.presentSomething(response: response)
    }
}
