//
//  DetailModels.swift
//  CleanSwift_GetData
//
//  Created by brian은석 on 2021/02/02.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Detail {
    // MARK: Use cases
    
    enum ShowDetail {
        struct Request{ }
        struct Response {
            var detail: Information.Detail
        }
        struct ViewModel {
            struct DisplayedDetail {
                var name: String
                var age: Int
            }
            var displayedDetail: DisplayedDetail
        }
    }
}
