//
//  DetailPresenter.swift
//  CleanSwift_GetData
//
//  Created by brian은석 on 2021/02/02.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailPresentationLogic {
    func presentSomething(response: Detail.ShowDetail.Response)
}

class DetailPresenter: DetailPresentationLogic {
    weak var viewController: DetailDisplayLogic?
    
    // MARK: Do something
    func presentSomething(response: Detail.ShowDetail.Response) {
        let detail = Detail.ShowDetail.ViewModel.DisplayedDetail.init(name: response.detail.name, age: response.detail.age)
        let viewModel = Detail.ShowDetail.ViewModel(displayedDetail: detail)
        viewController?.displayInfo(viewModel: viewModel)
    }
}
