//
//  ListInteractor.swift
//  CleanSwift_GetData
//
//  Created by brian은석 on 2021/02/02.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListBusinessLogic {
    func fetchData(request: List.FetchData.Request)
}

protocol ListDataStore {
    var informaions: [Information.Detail]? {get}
}

class ListInteractor: ListBusinessLogic, ListDataStore {
    var presenter: ListPresentationLogic?
    var worker: ListWorker?
    var informaions: [Information.Detail]?

    //2번
    func fetchData(request: List.FetchData.Request) {
        
        worker?.fetchInfomation(completionHandler: { [weak self ] list in
            
            self?.informaions = list
            let response = List.FetchData.Response(list: list)
            //4번
            self?.presenter?.presentFetchInfo(response: response)
        })
        
       
    }
}
