//
//  ListModels.swift
//  CleanSwift_GetData
//
//  Created by brian은석 on 2021/02/02.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum List {
  
  enum FetchData {
    struct Request { }
    struct Response {
        let list: [Information.Detail]
    }
    struct ViewModel {
        //셀에 넣어줘
        struct DisplayedInformation {
            let name:String
            let age: Int
        }
        var displayedList: [DisplayedInformation]
    }
  }
}
