//
//  ListWorker.swift
//  CleanSwift_GetData
//
//  Created by brian은석 on 2021/02/02.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum URLInformation: String {
    case getData = "https://us-central1-cleanswiftsample-c28fa.cloudfunctions.net/getFeeds"
}

class ListWorker {
    private var urlString: String!
    init(url:URLInformation) {
        urlString = url.rawValue
    }
    
    //3번 통신
    func fetchInfomation(completionHandler: @escaping ([Information.Detail]) -> Void) {
        let url = URL(string: urlString)!
        URLSession.shared.dataTask(with: url) { (data, response, error) in
            if let data = data, let response = response as? HTTPURLResponse, response.statusCode == 200 {
                        do {
                            let informations = try JSONDecoder().decode(Information.self, from: data)
                            
                            completionHandler(informations.feeds)

                        } catch(let err) {
                            print("Decoding Error")
                            print(err.localizedDescription)
                        }
                    }
        }.resume()
    }
}
