//
//  CreateTodoInteractor.swift
//  CleanTodo
//
//  Created by brian은석 on 2021/01/18.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateTodoBusinessLogic {
  func createdToDo(request: CreateTodo.CreateToDo.Request)
}

protocol CreateTodoDataStore
{
  //var name: String { get set }
}

class CreateTodoInteractor: CreateTodoBusinessLogic, CreateTodoDataStore
{
  var presenter: CreateTodoPresentationLogic?
  var worker = CreateTodoWorker(toDoStore: ToDoMemoryStore())
  //var name: String = ""
  
  // MARK: Do something
  
  func createdToDo(request: CreateTodo.CreateToDo.Request) {
    worker.createToDo(todoCreate: request.todo) {[weak self] (todo , error) in
        let response = CreateTodo.CreateToDo.Response()
        self?.presenter?.presentSomething(response: response)

    }
    
  }
    

}
