//
//  CreateTodoModels.swift
//  CleanTodo
//
//  Created by brian은석 on 2021/01/18.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CreateTodo
{
    enum CreateToDo {
        struct Request {
            var todo: ToDo
        }
        struct Response {
            var todo: ToDo?
        }
        struct ViewModel {
            var todo: ToDo?
        }
    }
}
