//
//  ListWorker.swift
//  CleanTodo
//
//  Created by brian은석 on 2021/01/16.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ListWorker {
    let toDoStore: ToDoStore
    init(toDoStore: ToDoStore){
        self.toDoStore = toDoStore
    }
    
    func updateCheckData(index:Int) -> List.FetchToDos.Response {
        let todos = toDoStore.updateCheckToDo(index: index)
        let response = List.FetchToDos.Response(list: todos)
        return response
    }
    //reload
    func fetchToDos(completionHandler: @escaping ([ToDo], ToDoStoreError?) -> Void) {
        toDoStore.fetchToDos { (todoList, error) in
            DispatchQueue.main.async {
                completionHandler(todoList, error)
            }
        }
    }

}
