//
//  ListPresenter.swift
//  CleanTodo
//
//  Created by brian은석 on 2021/01/16.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListPresentationLogic {
    func presentFetchToDos(response: List.FetchToDos.Response)
}

class ListPresenter: ListPresentationLogic
{
  weak var viewController: ListDisplayLogic?
  
  // MARK: Fetch something
  //presenter -> viewcontroller 푸쉬하는 느낌.
  func presentFetchToDos(response: List.FetchToDos.Response) {
    var displayedToDos: [List.FetchToDos.ViewModel.DisplayedToDo] = []
    for todo in response.list {
        let displayedToDo = List.FetchToDos.ViewModel.DisplayedToDo(
            title: todo.title, isChecked: todo.isChecked)
        displayedToDos.append(displayedToDo)
    }
    let viewModel = List.FetchToDos.ViewModel(displayedList: displayedToDos)
    viewController?.displayFetchedList(viewModel: viewModel)
  }
}
