# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AnimationOfT' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AnimationOfT
  pod 'ReactorKit'
  pod 'RxCocoa'
  pod "RxGesture"

  target 'AnimationOfTTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AnimationOfTUITests' do
    # Pods for testing
  end

end
