# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CounterMvvm1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'ReactorKit'
pod 'RxCocoa'
  # Pods for CounterMvvm1

end
